### ISSUE TITLE
Editor creates redundant/conflicting setup properties

### ISSUE THREAD

**Issue by yewang** [IlyaKirillov/GoProject#1]
When using the 'editor' tool (F3), adding a stone and then removing causes redundant and conflicting setup properties to be placed in the resulting SGF file. Also, duplicate properties are created within one node.

For example, adding a black stone in the top-left, then removing it results in:
AB[aa]AE[aa]
when there should simply just be nothing added to the SGF file. Repeating this results in an extend sequence of redundant/conflicting properties, for example:
AB[aa]AE[aa]AB[aa]AE[aa]

The SGF standard (http://www.red-bean.com/sgf/sgf4.html) specifies the following
 1. Duplicate properties within a node are forbidden. For example, all black stones added should be listed in a point list following one AB property (i.e., AB[aa][bb][cc] instead of AB[aa]AB[bb]AB[cc]).
 2. The points listed across AB, AW, and AE properties must be unique (i.e., AB[aa]AE[aa] is illegal).
 3. Editors should not rely on the ordering of properties within a node, which is not fixed and may be changed by other programs. For example, relying on AE[aa] coming after AB[aa] to clear the stone previously placed is not allowed and may be fragile to other programs that rearrange the order and/or fix the conflict error.

**Comment by IlyaKirillov** [comment]
fixed version 0.9.43. Thanks
