### ISSUE TITLE
are you guys working actively on a better score estimator?

### ISSUE THREAD

**Issue by danielb2** [IlyaKirillov/GoProject#10]
and awesome job. I love this extension :)

**Comment by IlyaKirillov** [comment]
Currently no. Btw, what do u mean by "better SE"? Automatically dead groups detection or something else?

PS: I'm the only one developer, so no "guys" just a guy xD

**Comment by danielb2** [comment]
I meant just being able to predict the score each person has. Right now pretty much only seems to detect points in ponuki and the like. It doesn't evaluate the score at all. 

OK, just one guy :P It's a tricky problem to solve, I know ;)

**Comment by IlyaKirillov** [comment]
Have u tried to mark dead groups?

**Comment by danielb2** [comment]
I had not. That's a great tip, but I'm thinking earlier on in games when it's harder see. I'm attaching example below. Compare OGS.

Also, how can I toggle coordinates?

![screen shot 2016-02-22 at 10 36 25](https://cloud.githubusercontent.com/assets/26678/13228334/3c2bdc78-d950-11e5-92a4-fbf024176e94.png)

![screen shot 2016-02-22 at 10 36 19](https://cloud.githubusercontent.com/assets/26678/13228339/3feabab4-d950-11e5-89b4-1f5b842644d0.png)

**Comment by danielb2** [comment]
Btw, the OGS version also says "White by 12.5".  Which I think is nice

**Comment by danielb2** [comment]
Ref: https://online-go.com/game/1529331

**Comment by IlyaKirillov** [comment]
It's seems like a bug. In my 48 version of Chrome it's looks like this 
![se](https://cloud.githubusercontent.com/assets/9784641/13228520/8daaa7a2-d9ad-11e5-8441-fe63b407b051.png)

Tell me pls ur browser with version numbers nad you OS.

About coordinates: trye Ctrl+R hotkey. There is help section with description page with all hotkeys.

**Comment by danielb2** [comment]
oh, my version is old. it's the one from the web store:  Web Go Board 0.10.0

_It works fine with estimator_.  I missed checking the hotkeys. I propose making everything that's accessible via hotkeys also accessible via the menu. A friend of mine asked me how to open a file, and I remember being initially confused by that too since there are only hotkeys for that.

**Comment by danielb2** [comment]
oh, and thanks :)

**Comment by danielb2** [comment]
btw, it would be cool if it were possible to also help the score estimator by marking

**Comment by IlyaKirillov** [comment]
You are able to do it right in SE window. Compare previous screenshot with this one 
![se2](https://cloud.githubusercontent.com/assets/9784641/13229192/b1f63862-d9b0-11e5-9806-86d9b6c10291.png)

**Comment by IlyaKirillov** [comment]
Btw, i'm going to release new version with menu button. There will be some most common functions, Like open/save and SE and some others.

**Comment by danielb2** [comment]
you're awesome. thank you :)
