### ISSUE TITLE
FF-50 заблокировал применение WGB

### ISSUE THREAD

**Issue by kvichans** [IlyaKirillov/GoProject#20]
После обновления до ФФ-50 плагин оказался отключенным. Беда.

**Comment by IlyaKirillov** [comment]
Обновился до 50 версии. Все нормально. Попробовал удалить расширение и заново поставить, опять-таки все нормально. Работало в обоих случаях, возможно у вас что-то не так с самим ФФ?

**Comment by kvichans** [comment]
Было
![wgb-block](https://cloud.githubusercontent.com/assets/7419630/20512987/2fed9c50-b094-11e6-84b7-94c11047e77b.PNG)
Помогло удаление и установка заново. Версия плагина (0.10.8) осталась прежней.

**Comment by IlyaKirillov** [comment]
Отлично. У меня все сразу было нормально, похоже после обновления версии они перепроверяли дополнения на совместимость сами, у ФФ такое бывает.
