### ISSUE TITLE
add a new event: onGameTreeModified + some other minor things

### ISSUE THREAD

**Issue by goplayerjuggler** [IlyaKirillov/GoProject#28]
add a new event: onGameTreeModified + some other minor things
Здравствуйте! и счастливый новый год! 
Great work Mr Kirillov!

I've been using your Firefox plugin for a few years now; it's been very handy. Thanks! благодаря!

Anyway I'm writing because I've hooked up your Web Go Board component to some [other code I've written](https://github.com/goplayerjuggler/goVariants/tree/master/transformer) for [Toroidal Go](https://senseis.xmp.net/?ToroidalGo). It's working pretty well. Here are some samples:
- [a viewer/editor](https://goplayerjuggler.github.io/goVariants/tGoEditor.html)
- [a blog post](https://goplayerjuggler.blogspot.com/2017/12/a-big-fight-in-t-go-game-same-game-but.html)

Related to this project, I have a few feature requests (fairly small I hope):
1) could CGoBoardApi be extended so as to expose an event called onGameTreeModified? The event would be raised after a modification is made to the game tree and after CGoBoardApi has finished its work related to that. A "nice to have" feature would be for the event to give some information on the change that was made (new node, delete node, update a node).

When the onGameTreeModified event is raised, my code will get the updated SGF and then make changes so it carries on "working" for toroidal Go. It would be equivalent to pressing the button "update all (t-Go SGF and board) (from board)" in the html [viewer/editor](https://goplayerjuggler.github.io/goVariants/tGoEditor.html). The main code for that is [here on git](https://github.com/goplayerjuggler/goVariants/tree/master/docs/tGoEditor.html).

2) could a setting doNotCountLiberties be added somehow? When doNotCountLiberties===true, then no stones would ever be removed by your go board after a move. Stones would only be removed when there are AE (add empty) nodes in the input SGF.

Having this setting should help me improve things by not having to replace move information in the SGF for t-Go (B[xy] and W[xy]) with "add stones" (AB, AW). That way, it will be possible to handle passes correctly in my sample (viewer.html).

3) Could a new action “add empty variation” be added? Perhaps it could be exposed with the shortcut Ctrl+Insert. That could be useful in general, not just in the context of t-Go, for setting up different diagrams as variations. 

4) (added 2018-01-12) add a setting so the hoshis, the four 10-4 points and the tengen do not have any special marking that distinguishes them from the other intersections.

By the way, this github issue supersedes the two [posts on life in 19x19](https://lifein19x19.com/viewtopic.php?p=226322#p226322) I made a few days ago.

Best,

Malcolm

**Comment by KirillovIlya** [comment]
Version 0.10.11

1. CGoBoardApi.Set_OnGameTreeModifiedCallback(oGameTree, function(){
alert("Test");
})

2. CGoBoardApi.Set_CapturingMode(oGameTree, isCapture);
Set isCapture flag  to "false"

3. Added new hotkey Ctrl+Ins for adding an empty node

4. CGoBoardApi.Set_DrawHandicapMarks(oGameTree, isDraw);
Set isDraw flag to "false"

Thank you.

**Comment by IlyaKirillov** [comment]
Version 0.10.11

CGoBoardApi.Set_OnGameTreeModifiedCallback(oGameTree, function(){
alert("Test");
})

CGoBoardApi.Set_CapturingMode(oGameTree, isCapture);
Set isCapture flag to "false"

Added new hotkey Ctrl+Ins for adding an empty node

CGoBoardApi.Set_DrawHandicapMarks(oGameTree, isDraw);
Set isDraw flag to "false"

Thank you.

**Comment by goplayerjuggler** [comment]
Thanks very much for this.
However I noticed a few things that could be improved.

1. When the capturing mode is switched off via `GoBoardApi.Set_CapturingMode(oGameTree, false)`, then liberty counting should be switched off when a move is played. So suicides should be allowed. This is not the case at present: set up a black ponuki and then try to make a white move inside it - it’s not allowed by the go board. 
	In some situations in Toroidal Go with wraparound, moves may appear to be a suicide but instead are not - the move captures the stones of the other colour.
1. Regarding `Set_OnGameTreeModifiedCallback`. 
	1. From my tests the callback function is called twice when a move is played. It would be better if it were only called once.
	1. The callback is called when it should not be called in the following scenario: the focus is on the Comments textarea, then another application is focused (via `Alt+Tab` for example), and then the browser is focused by `Alt+Tab` again.

**Comment by goplayerjuggler** [comment]
I saw you did something related the bug with suicides on 2018-03-09, but it's not in the 2018-03-03 / 0.10.11 build of goboardmin.js 
Any chance of you making a new build? Or letting me know how to make a build myself? Thanks.
