### ISSUE TITLE
Duplicate SGF properties

### ISSUE THREAD

**Issue by mkmatlock** [IlyaKirillov/GoProject#3]
Occasionally, the web board makes two entries for the same property (for example, two LB entries).

Your app appears to be written to combine the first LB entry in a node with the duplicate entries, but having two or more identical entries is actually illegal by the SGF standard, and many other applications explicitly enforce this, so they can't load the saved SGF output from Web Go Board.

The duplicate entries appear to occur in special circumstances in which one makes labels and then goes back and deletes some and then proceeds to make new labels. I'm not sure exactly how to reproduce it, but it has happened several times to me. 

Regardless, you should add a check in your SGF output for duplicate labels.

Here is an example SGF output from Web Go Board, which is illegal (you'll notice it contains the code ```LB[da:A]LB[af:B]```, which should be ```LB[da:A][af:B]``` instead):

```
(;GM[1]FF[4]CA[UTF-8]AP[goban.org]ST[2]SZ[19]KM[0]HA[0]PB[Black]PW[White]AB[cb][cc][cd][ce][be]AW[bf][df][cf][dd][dc][db][fb][bh][de]AE[bg][af][da]PL[W]LB[da:A]LB[af:B]C[Is A or B sente for white?](;W    [``]C[Both are sente. Black must respond or he dies unconditionally. (see variations)])(;W[da];B[``];W[ad];B[ae];W[ca];B[ba];W[bb];B[ab];W[bc]TR[da]C[Black plays tenuki with 2 and then dies.])(;W[af];    B[``];W[ae];B[ad];W[bc];B[bb];W[ca];B[ba];W[ab]TR[af]C[Again, black plays tenuki with 2 and then dies.]))
```

**Comment by IlyaKirillov** [comment]
fixed version 0.9.58. Thank you
