### ISSUE TITLE
How to create goboardmin.js?

### ISSUE THREAD

**Issue by goplayerjuggler** [IlyaKirillov/GoProject#31]
I would like to create goboardmin.js from a clone/fork of GoProject but I don't see how it could be done. What tool(s) do you use for this?

Thanks

**Comment by IlyaKirillov** [comment]
Sorry for very late answer. I'm using Google closure compiler.

**Comment by goplayerjuggler** [comment]
Better late than never! Would it be possible for you to give some details about how you make the call to the Google closure compiler? The command line you use? Sorry, I'm not very good with this sort of topic...

**Comment by goplayerjuggler** [comment]
No worries, thanks anyway!
I'm still using your code, I just made a new blog post:
https://goplayerjuggler.blogspot.com/2020/08/a-lucky-escape-and-tricky-whole-board.html

I was wondering if there was a way to delay loading/displaying your GoProject. 
Also I would like to have some way to control the width/position of the comment box.

Anyway, thanks again, I appreciate your work!
