### ISSUE TITLE
Pass move encoding is incorrect

### ISSUE THREAD

**Issue by mkmatlock** [IlyaKirillov/GoProject#4]
In the Web Go Board SGF output, pass moves are encoded as ```B[``]``` or ```W[``]```, but the ``` `` ``` characters are not valid SGF standard. These should be encoded as ```B[]``` or ```W[]```.

This causes other SGF software to crash or display the SGF incorrectly.

**Comment by IlyaKirillov** [comment]
fixed version 0.9.58. Thank you
