### ISSUE TITLE
Stream issue

### ISSUE THREAD

**Issue by Smike16** [IlyaKirillov/GoProject#5]
Hello, Kosmo. The main issue here, that you are not streaming Go matches anymore. Now I do see, what you were doing all this time. 

I'm still waiting for your streams!

<3 KOCMO <3

**Comment by IlyaKirillov** [comment]
:) I will continue streaming for sure. I'm not going to close this issue, this will be the best reminder for me.

**Comment by IlyaKirillov** [comment]
fixed :)  https://www.youtube.com/watch?v=M3rAc7sMiAI

**Comment by Smike16** [comment]
Love you <3

btw. you did a great job, KOCMO

**Comment by KirillovIlya** [comment]
Thanks xD
