### ISSUE TITLE
Move a branch up or down in priority

### ISSUE THREAD

**Issue by mkmatlock** [IlyaKirillov/GoProject#7]
It would be really nice to be able to move branches up and down in priority.

For example, sometimes I want to present variations in a particular order, but I forget to make one variation before another. I usually go back and delete the first variation and remake it so it appears second. It would be nice to be able switch their order without this labor.

**Comment by IlyaKirillov** [comment]
Wait for next update, but now u can consider to use Ctrl+Shift+M hotkey (Make the current variant mainly)

**Comment by IlyaKirillov** [comment]
fixed 
https://github.com/IlyaKirillov/GoProject/commit/72d3eced4191f076ddd436050330e3f68040a0f4

Hotkey for lift up/lower down is Ctrl+Shift+U/D.

Thank you.
