### ISSUE TITLE
Is it possible to save on localStorage from the Chrome Extension, instead of just saving as files?

### ISSUE THREAD

**Issue by fiatjaf** [IlyaKirillov/GoProject#8]
That would help me manually transcribing games.

I imagine it would be a simple thing to add. If you can help me showing where is the code for the extension I can submit a PR.

Thank you very much.

**Comment by IlyaKirillov** [comment]
Do u need to have possibility to save one certain file to localStorage instead of local saving?
I can do it, but it won't work between different browsers and different pc's, i mean saved game could be opened only on PC and browser which it had saved.

**Comment by fiatjaf** [comment]
I know that. It's just that I feel a lot more confort when editing a game (with commentary, variations etc.) if I can save every time, otherwise the PC can shutdown unexpectedly, or the browser can close, or I can press some key unintentionally and lose everything.

Some dasy ago I was editing a game and trying to learn the shortcuts at F3, F4, F7 etc. Then I pressed F5. Bam. The page reloaded. I lost everything.

Saving with Ctrl+S gets me a new file downloaded every time, which makes a lot of confusion on my computer (I ended up deleting the most recently saved file some other day, when cleaning the mess).

**Comment by IlyaKirillov** [comment]
I got ur idea, rly like it. I will do it in the next update.

**Comment by fiatjaf** [comment]
Thank you very much.

**Comment by IlyaKirillov** [comment]
fixed version 0.10.5
